name: Network Validation
on:
  workflow_dispatch:

jobs:
  network-validator:
    runs-on: ubuntu-latest
    services:
      op-connect-api:
        image: 1password/connect-api:latest
        ports:
          - 8080:8080
        volumes:
          - op-data:/home/opuser/.op/data
        env:
          OP_SESSION: ${{ secrets.OP_CREDENTIALS_B64 }}
      op-connect-sync:
        image: 1password/connect-sync:latest
        ports:
          - 8081:8080
        volumes:
          - op-data:/home/opuser/.op/data
        env:
          OP_SESSION: ${{ secrets.OP_CREDENTIALS_B64 }}
    steps:
    - uses: actions/checkout@v3
    - name: Configure 1Password Connect
      uses: 1password/load-secrets-action/configure@v1
      with:
        connect-host: http://localhost:8080
        connect-token: ${{ secrets.OP_CONNECT_TOKEN }}
    
    - name: Load Tailscale Secrets
      uses: 1password/load-secrets-action@v1.2.0
      env:
        TAILSCALE_AUTHKEY: op://jtcressy-net-infra/tailscale-key-ghactions/password

    - name: Tailscale
      uses: tailscale/github-action@16d7e0b7812f55e668628a71630a09956522baa9
      with:
        authkey: ${{ env.TAILSCALE_AUTHKEY }}